<?php namespace ProcessWire;

/**
 * PageListExtras
 *
 * @author Robin Sallis
 * @credits Based on PageListShowPageId by Philipp Urlich "Soma"
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class PageListExtras extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Page List Extras',
			'version' => '0.1.4',
			'summary' => 'Adds page ID and template name to the page list, for superuser only.',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/PageListExtras',
			'icon' => 'ellipsis-h',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		if($this->user->isSuperuser()){
			$this->addHookAfter('ProcessPageListRender::getPageLabel', $this, 'addExtras');
			$this->addHookAfter('ProcessController::execute', $this, 'addStylesheet');
		}
	}

	/**
	 * Add extras
	 *
	 * @param HookEvent $event
	 */
	public function addExtras(HookEvent $event){
		$page = $event->arguments(0);
		$options = $event->arguments(1);
		// Return if this label is for the Tree dropdown menus
		if(!empty($options['noTags'])) return;
		$event->return .= " <span class='helper-info'>($page->id, $page->template)</span> ";
	}

	/**
	 * Add stylesheet
	 *
	 * @param HookEvent $event
	 */
	public function addStylesheet(HookEvent $event){
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config = $this->wire()->config;
		$config->styles->add($config->urls->$this . "{$this}.css?v=$version");
	}

}
